parameters:
  PathProyect: default
  ServiceConnection: default
  ResourceGroupTerraform: default
  StoregeAccountTerraform: default
  TerraformContainer: default
  TerraformFile: default

stages:
- stage: Build
  jobs:
  - job: 'Build_Terraform'
    steps:

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform latest'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: 'Terraform : init'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)$(PathProyect)'
        backendServiceArm: $(ServiceConnection)
        backendAzureRmResourceGroupName: $(ResourceGroupTerraform)
        backendAzureRmStorageAccountName: $(StoregeAccountTerraform)
        backendAzureRmContainerName: $(TerraformContainer)
        backendAzureRmKey: $(TerraformFile)

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: 'Terraform : validate'
      inputs:
        command: validate
        workingDirectory: '$(System.DefaultWorkingDirectory)$(PathProyect)'