parameters:  
  ServiceConnection: default
  ResourceGroupTerraform: default
  StoregeAccountTerraform: default
  TerraformContainer: default
  TerraformFile: default
  FileVar: default

stages:
- stage: Deploy
  jobs:
  - job: 'Deploy_Terraform'
    steps:

    - task: DownloadPipelineArtifact@2
      displayName: 'Get Artifact'
      inputs:
        artifact: drop
        path: $(Build.ArtifactStagingDirectory)        

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : plan'
      inputs:
        command: plan
        workingDirectory: '$(Build.ArtifactStagingDirectory)'
        commandOptions: '-var-file=$(FileVar)'
        environmentServiceNameAzureRM: $(ServiceConnection)   

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : apply'
      inputs:
        command: apply
        workingDirectory: '$(Build.ArtifactStagingDirectory)'
        commandOptions: '-var-file=$(FileVar)'
        environmentServiceNameAzureRM: $(ServiceConnection)  

    - script: | 
        cd $(Build.ArtifactStagingDirectory)
        ls        
      displayName: ejemplo        
