parameters:  
  ServiceConnection: default  
  FileVar: default

stages:
- stage: Deploy
  jobs:
  - job: 'Deploy_Terraform'
    steps:

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : plan'
      inputs:
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)$(PathProyect)'
        commandOptions: '-var-file=$(FileVar)'
        environmentServiceNameAzureRM: $(ServiceConnection)   

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : apply'
      inputs:
        command: apply
        workingDirectory: '$(System.DefaultWorkingDirectory)$(PathProyect)'
        commandOptions: '-var-file=$(FileVar)'
        environmentServiceNameAzureRM: $(ServiceConnection)  

    - script: | 
        cd '$(System.DefaultWorkingDirectory)$(PathProyect)'
        ls        
      displayName: ejemplo        
