parameters:  
  ServiceConnection: default
  ResourceGroupTerraform: default
  StoregeAccountTerraform: default
  TerraformContainer: default
  TerraformFile: default

stages:
- stage: Deploy
  jobs:
  - job: 'Deploy_Terraform'
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(System.ArtifactsDirectory)'    

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform latest'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
      displayName: 'Terraform : init'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceArm: $(ServiceConnection)
        backendAzureRmResourceGroupName: $(ResourceGroupTerraform)
        backendAzureRmStorageAccountName: $(StoregeAccountTerraform)
        backendAzureRmContainerName: $(TerraformContainer)
        backendAzureRmKey: $(TerraformFile)

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
        displayName: 'Terraform : azurerm'
        inputs:
          command: apply
          environmentServiceNameAzureRM: $(ServiceConnection)      